//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Git4Win.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Git4Win.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static System.Drawing.Icon Change0 {
            get {
                object obj = ResourceManager.GetObject("Change0", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon Change1 {
            get {
                object obj = ResourceManager.GetObject("Change1", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon git {
            get {
                object obj = ResourceManager.GetObject("git", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static byte[] pageant {
            get {
                object obj = ResourceManager.GetObject("pageant", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] plink {
            get {
                object obj = ResourceManager.GetObject("plink", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] puttygen {
            get {
                object obj = ResourceManager.GetObject("puttygen", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static System.Drawing.Icon TreeIcon1 {
            get {
                object obj = ResourceManager.GetObject("TreeIcon1", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon TreeIcon10 {
            get {
                object obj = ResourceManager.GetObject("TreeIcon10", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon TreeIcon11 {
            get {
                object obj = ResourceManager.GetObject("TreeIcon11", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon TreeIcon2 {
            get {
                object obj = ResourceManager.GetObject("TreeIcon2", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon TreeIcon3 {
            get {
                object obj = ResourceManager.GetObject("TreeIcon3", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon TreeIcon4 {
            get {
                object obj = ResourceManager.GetObject("TreeIcon4", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon TreeIcon5 {
            get {
                object obj = ResourceManager.GetObject("TreeIcon5", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon TreeIcon6 {
            get {
                object obj = ResourceManager.GetObject("TreeIcon6", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon TreeIcon7 {
            get {
                object obj = ResourceManager.GetObject("TreeIcon7", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon TreeIcon8 {
            get {
                object obj = ResourceManager.GetObject("TreeIcon8", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon TreeIcon9 {
            get {
                object obj = ResourceManager.GetObject("TreeIcon9", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
